package com.example.trip

object Constants {
    const val GROUP_ID_KEY = "groupId"
    const val ATTRACTION_KEY = "attraction"
    const val EXPENSE_KEY = "expense"
    const val DAY_PLAN_KEY = "dayPlan"
    const val GROUP_KEY = "group"
    const val ACCOMMODATION_ID_KEY = "accommodationId"
    const val USER_TRANSPORT_KEY = "userTransport"
    const val STATUS_KEY = "status"
    const val CURRENCY_KEY = "currency"
    const val START_CITY = "startCity"
    const val SUMMARY_FILE_NAME = "summary.pdf"
    const val BASE_URL = "http://10.0.0.11:8080/api/v1/"
    const val AUTHORIZATION_HEADER = "Authorization"
    const val PREFERENCES_NAME = "AppPreferences"
    const val GOOGLE_API_KEY = "com.google.android.geo.API_KEY"
    const val DESTINATION_KEY = "destination"
    const val START_CITY_KEY = "startCity"
    const val USER_ID_KEY = "userId"
    const val COORDINATORS_KEY = "coordinators"
    const val ACCOMMODATION_KEY = "accommodation"
    const val ATTRACTION_PREVIEW_KEY = "attractionPreview"
    const val DAY_PLAN_ID_KEY = "dayPlanId"
    const val PARTICIPANT_KEY = "participant"
    const val TO_REFRESH_KEY = "refresh"
    const val LOCATION_KEY = "Location"
}